### ISSUE TITLE
Still have problems

### ISSUE THREAD

**Issue by dapdapkill** [ZoDDeL/CM-Ultimate#14]
It still has the symptom of bouncing out of the game.

**Comment by 1040302** [comment]
I can confirm that their new anti-cheat system has completely messed things up. Crashes don't just happen when you open CE; it seems that even having it installed will trigger detection. To play this game, you need to uninstall all cheat software and even mobile emulators. What a genius idea. Even more brilliant is the fact that they haven’t provided a specific list of prohibited software.The community is now flooded with crash reports, and most people don’t even realize that the crashes are caused by the anti-cheat system. I honestly have no words for this.

**Comment by 1040302** [comment]
For PC players, this update is an absolute disaster. According to methods summarized by the community, to launch the game stably, you need to shut down almost all software, including but not limited to peripheral drivers like Logitech, game overlay software like XGP, and even Wallpaper Engine. On top of that, it seems browsers can also trigger detection if a website contains "cheat" in the URL. They are truly geniuses.

**Comment by ZoDDeL** [comment]
yep close everything before starting the game.
close steam (you can run the game with its own exe)
discord, afterburner/rtss, reWASD(maybe uninstall it because of the driver/service),
browser, any open file/folder.

i can play the game for hours if i close everything.
when i have my browser open or livestream with obs to youtube the game closes in a few minutes.

if nothing else work try a fresh windows installation (i suggest windows 10)
and install nothing beside the nessary drivers and steam (and cheat engine + plugin if you wanna use my table).
you can copy the game folder to another harddrive/usb stick etc.

**Comment by dapdapkill** [comment]
For me it's not a problem. Because I have already arranged various weapons. The only problem is the large map that I only use to indicate the location. for me version 19.4 is enough.
